Level Up Screen Reward Magic
GlowLimeGames/DefendersLight pull request #100
Opened 2016-11-15 21:18 UTC by dkhopez

2016-11-15 21:30 UTC, imann24 requested changes

2016-11-15 21:30 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        yield return new WaitForSeconds(5);
Can this be a public integer so that it's tunable?

2016-11-15 21:30 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        Instantiate(LevelUpScreen);
Can you make sure the LevelUp screen is hidden by default (should not be visible in the scene when the game is not running)

2016-11-15 21:30 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +public class LevelUpRewardScreenController : UIController {
The canvas appears to be blocking raycasts to the build button. Can you add a CanvasGroup component to it and uncheck "BlocksRaycasts?"

2016-11-15 21:35 UTC, dkhopez commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        yield return new WaitForSeconds(5);
All that is old code...

2016-11-15 21:35 UTC, dkhopez commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        yield return new WaitForSeconds(5);
Idk how that got there

2016-11-16 00:24 UTC, imann24 requested changes

2016-11-16 00:24 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        yield return new WaitForSeconds(5);
Gotcha. Very curious

2016-11-16 00:24 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        if (Leveled)
We shouldn't have to check this in update. Can you use the Event subscription model or a Singleton var instead?

2016-11-16 00:24 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        //text.text = "";
Can you remove any commented out lines?

2016-11-16 00:24 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        text.text = "LEVEL UP!";
Can you make this a public variable in the class so it's tunable from the Inspector?

2016-11-16 00:24 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +        yield return new WaitForSeconds(5);
Can you make this a public variable in the class so it's tunable from the Inspector?

2016-11-18 04:07 UTC, imann24 commented on Assets/Scripts/UserInterface/GameUI/LevelUpRewardScreenController.cs
> +    void Update()
So this is the one thing I'd still like to change. Ideally we're not using the "Update" method for anything that doesn't require constant changes (e.g. animation). There are definitely ways you can accomplish this same functionality without checking in update, e.g. using an EventController call or by making a `public static LevelUpRewardScreenController Instance;` var that you reference in the other script

2016-11-18 04:37 UTC, merged